### ISSUE TITLE
bypass

### ISSUE THREAD

**Issue by Tamago4a** [Faeety/CustomDoorAccess#1]
If you set any other values to a specific door, the bypass will no longer work on that door.

**Comment by Faeety** [comment]
Are you talking about the bypass button in the RA ?

**Comment by Tamago4a** [comment]
Yes of course.

**Comment by Faeety** [comment]
It will be fix asap, I'm busy at the moment, I'll try to fix this this evening ! Sorry for the wait!

**Comment by Tamago4a** [comment]
Yes, I understand. You may not be in a hurry, you do it voluntarily.

**Comment by Faeety** [comment]
fixed ! Thanks for the report
